### ISSUE TITLE
Misprint?

### ISSUE THREAD

**Issue by Vairel** [idlesign/torrentool#10]
https://github.com/idlesign/torrentool/blob/78c474c2ecddbad2e3287b390ac8a043957f3563/torrentool/torrent.py#L368

This condition is never executed.

**Comment by idlesign** [comment]
Yeap, never executed. That part was meant to be a restriction for adaptive (calculated using files number and size or user defined) limits. However since where were no users in a need of such a feature, its not implemented.

**Comment by Vairel** [comment]
ok =)
