### ISSUE TITLE
Permitions help.

### ISSUE THREAD

**Issue by romanoh** [idlesign/torrentool#14]
I am learning python, and need a little help.

when i make a torrent in C:, it shows an "PermissionError: [Errno 13] Permission denied:" what can it be?

Also can it create private torrents (disabled DHT)?

**Comment by idlesign** [comment]
Try no create torrent not in the root directory but somewhere else, where permissions are not so strict.
DHT is related to torrent client, not torrent file, but `private` flag for file is supported.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
