### ISSUE TITLE
if file name have some strings samewith path, it will be delete

### ISSUE THREAD

**Issue by xiashengcnwh** [idlesign/torrentool#18]
hello
i am using python3.9
i have some files named by '[date] xxxxx,zip'
then, i create torrent by
 torrent = Torrent.create_from('/'+ date+ '/')
 torrent.to_file('my.torrent')
but i cant hash it with torrent client, then i find all file name in torrent has been 
change to '[] xxxxx,zip', 'date' be deleted
i try to use old torrentool, version before 1.1.0 dont have this problem, but folder in torrent named as '_',mabye its problem of python or other requments version?
and, may i create_torrent by an dict?
i want add multi files but i dislike folder in torrent

thank you

**Comment by idlesign** [comment]
Hi,

The described behaviour is strage indeed. It seems that something is missing from your description, or there's a problem with file naming (e.g. why do you have comma in `[date] xxxxx,zip`).
Please give some real file names (a listing) and a resulting torrent file.

**Comment by idlesign** [comment]
Seems to be related to #20

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
