### ISSUE TITLE
I got a wrong value of info_hash from a torrent file

### ISSUE THREAD

**Issue by sungold2020** [idlesign/torrentool#23]
[temp.zip](https://github.com/idlesign/torrentool/files/8636880/temp.zip)
There is a torrent file,  the info_hash from torrentool is "90005b48ee3680fe19a3ba365286e620a1c28e94"。but after I added it to qbittorrent, the real value of hash I got from qbittorrent is "cd83facad1b0ca0670a4612312a62ac259d96cf3".

**Comment by idlesign** [comment]
This file seems to be malformed: neither transmission nor online https://www.tools4noobs.com/online_tools/torrent_decode/ is able to parse it.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
