### ISSUE TITLE
Missing properties: "source"

### ISSUE THREAD

**Issue by kaypoush** [idlesign/torrentool#24]
Some properties for example `source` seems to be missing. `source` is useful for cross seeding and for some trackers it's a requirement.

**Comment by idlesign** [comment]
And what do you mean by `source` exactly? 
Any spec for that maybe?

**Comment by kaypoush** [comment]
It's a string key in `info` dictionary. I don't think there is any spec. I think it's a custom key but widely used. Most torrent clients have it as an option during the torrent creation process. It's basically a field where you enter the name of the torrent site or its acronym. For some private trackers it's a requirement. It can also be used to differentiate torrent files for cross seeding. [Here](https://github.com/qbittorrent/qBittorrent/issues/7965) is some additional explaining.

This is how it looks:

<img width="601" alt="Capture d’écran 2023-02-27 à 23 16 24" src="https://user-images.githubusercontent.com/9743162/221699621-26ef28e8-1d9a-4835-858b-8efc3ed0130d.png">

mktorrent [describes](https://github.com/pobrn/mktorrent/blob/de7d011b35458de1472665f50b96c9cf6c303f39/CHANGELOG.md) it like this:

> Option for source string added to torrent info (-s), included in infohash. Often used by private trackers to create a unique infohash to prevent peer-leak and the possibility to track the trackers that do use leaked torrents. Having this option in mktorrent make it possible to create a infohash accurate torrent to the tracker you want to upload it to

**Comment by idlesign** [comment]
It indeed looks similar to `comment` entry, which is mainly used just for torrent URIs on private trackers.
Yet we support this property as well.

Pull request is welcome.

**Comment by idlesign** [comment]
Considered closed by #27
