### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by oyjcmyn** [idlesign/torrentool#25]
Sometimes when parsing torrent files, an IndexError: pop from empty list error may occur. The torrent file appears to be fine since it can be opened and downloaded normally.
This torrent file cannot be parsed correctly：
[88.torrent.zip](https://github.com/idlesign/torrentool/files/11102838/88.torrent.zip)

**Comment by idlesign** [comment]
Thank you for the report.
We'll see what's the cause.

**Comment by oyjcmyn** [comment]
Okay, thank you very much.

**Comment by oyjcmyn** [comment]
Can you please fix this bug so I can use torrentool? I really want to use it.

**Comment by oyjcmyn** [comment]
"Using bencodepy, the 88.torrent file can be parsed correctly. Should we consider replacing bencode with bencodepy?

**Comment by idlesign** [comment]
This file contains garbage data `errot: no is id`. 

Since this case is not covered by the bencode specification as far as I know, I see no reason to hide this fact (though we could have do so in potentia) and allow some arbitrary data as a hidden (and possibly malicious) payload.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
