### ISSUE TITLE
Local tracker

### ISSUE THREAD

**Issue by MrNonoss** [idlesign/torrentool#31]
Hi, thank you for this cool project.
I would like to use it to share files amongst my local network, without internet access.
How can I setup a local tracker?

**Comment by idlesign** [comment]
Hi. I'm afraid torrentool won't help you with that task.
You'll need to find some tracker-server software. You can try to search github for `BitTorrent tracker`.

**Comment by MrNonoss** [comment]
Thanks for the comment.
You're right, maybe not the correct tool for my need.
